### ISSUE TITLE
Addon is not context aware

### ISSUE THREAD

**Issue by hugo-a-garcia** [davedoesdev/shared-memory-disruptor#2]
The addon is not context aware. This prevents it to be loaded multiple time as when using multiple worker threads from the same application.

Reference:
[Context-aware addons](https://nodejs.org/api/addons.html#addons_context_aware_addons)

**Comment by davedoesdev** [comment]
@hugo-a-garcia thanks for the pointer, I'll look into it

**Comment by davedoesdev** [comment]
I'll try this out in a test. It doesn't store any global state so shouldn't need the context.

**Comment by davedoesdev** [comment]
@hugo-a-garcia it works in multiple worker threads for me.

I added a test for it in https://github.com/davedoesdev/shared-memory-disruptor/commit/5b5bc41e4555c040ec301a8b0d9b2fa9362ea118

Does this test pass for you?

**Comment by davedoesdev** [comment]
Since we're defining a class and state is completely defined in each instance of the class, we should be fine. There's no state maintained by the addon across instances.

The [tests across multiple workers](https://github.com/davedoesdev/shared-memory-disruptor/blob/master/test/multi_workers.js) pass. @hugo-a-garcia feel free to re-open if multiple workers are failing for you.
